### ISSUE TITLE
Add .travis-yml to automatically validate PRs

### ISSUE THREAD

**Issue by bendoh** [oomphinc/scss-scaffold#16]
Since this is a public repository we get free CI through Travis CI. Let's leverage that.

**Comment by johncionci** [comment]
How would this work, be implemented, and whats the benefit?

**Comment by jhogue** [comment]
Can we run a SASS Linter to all PRs once they are opened? Maybe this is a good thing to also do on PHP files, but obis. we only want to concentrate on SASS style/syntax right now.

**Comment by johncionci** [comment]
@bendoh Can we get something on the calendar to chat about this? I think that it circles into the conversation that we are suppose to have to the Engineering Team as well.
