### ISSUE TITLE
Update modernizr touch call to touchevent for 3.3.1

### ISSUE THREAD

**Issue by nicholemaureen** [oomphinc/scss-scaffold#17]

**Comment by bendoh** [comment]
touching

**Comment by jhogue** [comment]
This is a good issue to update, as your touch-hover() mixing additions are good and I believe you maintained the variables for modernize class hooks.

**Comment by johncionci** [comment]
@nicholemaureen @jhogue I think you guys have updated this correct?

**Comment by nicholemaureen** [comment]
Not I

**Comment by jhogue** [comment]
I will take this on

**Comment by johncionci** [comment]
@jhogue Not sure if this is done but code you also take into account a generic fallback for sites that do not use Modernizr? Im working on WASHfunders and they do not have that on their platform so all the refs to `touch-hover()` in the scaffold need to be overridden.

**Comment by jhogue** [comment]
Hmmm. Without modernizr, the mixin is pretty useless. A simple fallback could look like: 

    @if $state == 'hover' {
		&:hover,
		&:focus {
			@content;
		}
	}

**Comment by jhogue** [comment]
I can update this further and employ a fallback if we do not have modernizr present, so you can run the same mixin (and not have to change all the calls manually) but get around the `.js` stuff.

**Comment by jhogue** [comment]
Closed by #28
