### ISSUE TITLE
Rethink Buttons Component Handling

### ISSUE THREAD

**Issue by johncionci** [oomphinc/scss-scaffold#30]
If we use the built Bourbon mixin that only account for buttons that are inputs. We still need to account for the same styles to be applied to action links that look like buttons.

Possibly consolidate one button mixin to handle both options and potentially move this into `_forms` or into `base` as they are a basic component of every site.

**Comment by jhogue** [comment]
I like having a `_buttons.scss` file dedicated. Some sites are simple, but most sites have at least three button styles and BCBS has like a million of them. 

My approach for BCBS was to focus on extensibility. So I defined the style variations as a set of mixins. First, the base mixin used by all others to account for padding, font style, the basic stuff. Each subsequent mixin included that as well as the styles that made it different, like color and text-transform or font-size. Finally, I applied these to a set of generic `button` classes. 

The mixins allow you to use them elsewhere when you can not apply the `button button--style-name` classes directly. When you can control the markup, you can apply the classes instead. 

I have been more of a fan of declaring them with classes, not elements. But I can see why adding styles via the `input[type="submit"], input[type="reset"], input[type="button"], button` declaration might be needed. 

Can I start on an approach based on the above and we can go from there? 

cc @nicholemaureen @kbeck303 @BrandonDH @syzygy333

**Comment by jhogue** [comment]
Link to the BCBS buttons file: https://github.com/oomphinc/bcbs.com/blob/master/src/scss/component/_buttons.scss

**Comment by kbeck303** [comment]
Used something similar on AskBlue,  I think I had copied it and expanded upon it from @johncionci 's  Genescape code

AskBlue buttons file: 
https://github.com/oomphinc/askblue2016/blob/master/src/scss/component/_buttons.scss

**Comment by kbeck303** [comment]
I like the idea of an expandable button mixin

**Comment by johncionci** [comment]
My main concern here was that we typically have "action links" that are suppose to look like buttons, and then we have actual input buttons and did not want to duplicate the code in both places, at the same time make sure that we had a distinction between the two. WASH is def smaller project than BCBS so I may have gotten their with this:

https://github.com/oomphinc/WASHfunders/blob/jc-blog-template/src/scss/component/_buttons.scss

Maybe theres a combo of the ideas that will work effectively.

**Comment by jhogue** [comment]
Taking this on today.
