### ISSUE TITLE
Consider a better way to organize files

### ISSUE THREAD

**Issue by jhogue** [oomphinc/scss-scaffold#40]
The 7/1 structure: https://sass-guidelin.es/#architecture

This structure does not immediately help us, as we typically do not use "themes" and try to keep "pages" from being too unique, though there are some merits to this structure as well. I propose something similar for us, a 6/1 pattern: 

|- abstracts/
|   |– _breakspoints.scss 
|   |– _colors.scss 
|   |– _helpers.scss 
|   |– _typesizes.scss 
|   |– _variables.scss 
|– base/
|   |– _reset.scss        # Reset/normalize
|   |– _typography.scss   # Typography rules
|- components/
|   |– _buttons.scss
|   |– _forms.scss
|   |– _header.scss
|   |– _footer.scss
|   |– _etc…
|- layout/
|   |– _header.scss
|   |– _grid.scss
|   |– _footer.scss
|   |– _sidebar.scss…
|   |– _etc…
|– pages/
|   |– _home.scss         # Home specific styles
|   |– _contact.scss      # Contact specific styles
|   |– _etc…
|-vendor/
|   |– _bourbon
|   |– _neat
|   |– _etc…
– main.scss

**Comment by johncionci** [comment]
Got my vote

**Comment by nicholemaureen** [comment]
Mine too

Nichole Frazier
UX ENGINEER
nfrazier@oomphinc.com
oomph.is/nfrazier <http://www.oomph.is/nfrazier>
@nicholemaureen_ <https://twitter.com/nicholemaureen_>[image: Twitter]

**Comment by johncionci** [comment]
@jhogue @nicholemaureen @kbeck303 @BrandonDH @syzygy333 

In an effort to further streamline the scaffold, does anyone think the we need `_accessibilty.scss` file all on its own? I think we keep it if theres anything that we will be adding from the Accessibility Initiative, but if not, we could make it a section in `global.scss`?

**Comment by BrandonDH** [comment]
@johncionci I think moving it to `global.scss` makes sense.

**Comment by jhogue** [comment]
@johncionci I'd be interested in your feelings here once you work with the Coolidge a little bit more. I know you decided to use this new pattern as you work on the Coolidge.
