### ISSUE TITLE
Remove Bourbon/Neat?

### ISSUE THREAD

**Issue by jhogue** [oomphinc/scss-scaffold#46]
Since Bourbon has basically deprecated everything that we use (http://bourbon.io/docs/) and Neat is no longer as necessary because of Flexbox, should we just rip it out and install an auto-prefixed into our asset pipeline? 

https://github.com/postcss/autoprefixer

Benefit: We write clean CSS3 compliant CSS and control all of the backwards compatibility for older browser in the build pipeline. 

Drawback: ?

@johncionci @BrandonDH @nicholemaureen @kbeck303 @syzygy333

**Comment by johncionci** [comment]
I thought we had Autoprefixer in some projects already but who knows they are all different but make sense if we are definitely moving away from Bourbon & Neat

**Comment by jhogue** [comment]
I'm going to start working in this… my approach will be the take out Bourbon/Neat from my local and see what breaks. I will then either add the missing functions to our Mixins if I think we want them long term, or I will remove references to the broken functions if it can be covered by Autoprefixer. 

I won't merge the branch until we have Autoprefixer (or something similar) in place in the build process.  

@johncionci @BrandonDH @nicholemaureen @kbeck303 @syzygy333
CC: @balbuf @marcaddeo

**Comment by jhogue** [comment]
Hackday work commences.
